export const environment = {
  production: true,
  baseUrl: 'https://uatekycfrontapi.arihantcapital.com/uat/', // PHYSICAL UAT
  baseUrlOfUser: 'https://uatekycfrontapi.arihantcapital.com/uat/', // PHYSICAL UAT
  image_upload_url: 'https://gwm1a0mt08.execute-api.ap-south-1.amazonaws.com/uat/', // PHYSICAL UAT
  common_upload: 'https://s7x44f3v4b.execute-api.ap-south-1.amazonaws.com/uat/',
  languageParamUrl: 'https://uatmobile.arihantplus.com/assets/', // dev-site Live
  manualKycUrl: 'https://zdqa4rfn2b.execute-api.ap-south-1.amazonaws.com/uat/api/processForMannualKYC',
  client_id: 'AVAC046847', // uatmobile.arihantplus.com =AVAC046847 Arihant UAT = 35C660C5 // Arihant UAT = 35C660C5  // uatmobile.arihantcapital.com = YL450ABC9D
  redirect_uri: 'https://uatmobile.arihantplus.com/redirect', // dev-site Live
  golapp: 'http://goldapp.getprosper.in', // Gold app Live
  logo_url: 'assets/images/logo.png', // dev-site Live
  logo_url_wt: 'assets/images/logo.png', // dev-site Live
  login_redirect_page: 'https://www.arihantplus.com',
  explore_web_url: 'https://home.getprosper.in/explore',
  mutualfund_web_url: 'https://home.getprosper.in/product-mutualfund',
  aboutus_web_url: 'https://home.getprosper.in/aboutus',
  home_url: 'https://home.getprosper.in',
  goals_url: 'https://home.getprosper.in/goals',
  calculators_url: 'https://home.getprosper.in/calculators/sip',
  culture_url: 'https://home.getprosper.in/culture',
  career_url: 'https://home.getprosper.in/careers',
  faq_url: 'https://home.getprosper.in/faq/account-opening',
  nfo_url: 'https://home.getprosper.in/nfo',
  googleSignUpUrl: 'https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&prompt=consent&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fplus.me%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&response_type=code&client_id=1083499708270-min6j00pms41kckoojhn9qaea8r1s9pl.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A4200%2Fgoogle',
  facebookSignupUrl: 'https://www.facebook.com/v4.0/dialog/oauth?auth_type=rerequest&client_id=1342908959408435&display=popup&redirect_uri=https%3A%2F%2Fsignin.getprosper.in%2FfaceBook&response_type=code&scope=email',
  appleSignupUrl: 'https://appleid.apple.com/auth/authorize?response_type=code&state=state&client_id=in.getprosper.devsite.service&redirect_uri=https%3A%2F%2Fdevsite.getprosper.in%2FappleRedirect&scope=openid+',
  blogUrl: 'https://www.uidai.gov.in/hi/media-resources-hi/resource-hi/video-hi/13717-tutorial-how-to-add-update-mobile-number-in-aadhaar.html',
  login_type: 'Mobile_OTP',
  client_name: 'arihant',
  esignActionUrl: 'https://esign.egov-nsdl.com/nsdl-esp/authenticate/esign-doc/',
  needHelp: 'https://support.arihantcapital.com/support/solutions/33000138462',
  addressKnowMore: 'https://support.arihantcapital.com/support/solutions/33000138462',
  termsConditionUrl: 'https://www.arihantcapital.com/termsandconditions',
  faqUrl: 'https://support.arihantcapital.com/support/solutions/33000138462',
  clientLogin: 'https://web.arihantplus.com/base/login-name',
  androidLink: 'https://play.google.com/store/apps/details?id=com.msf.acml',
  iosLink: 'https://apps.apple.com/in/app/arihant-plus/id1643484698',
  footerSiteUrl: 'https://arihantcapital.com',
  idArihantPlus: 'arihantplus',
  autoRefresh: 1,
  googleClientID: '1029211558465-bhgt24u9ecsr2ov6dpfpg577mk2n2a2f.apps.googleusercontent.com',
  logoutRedirectUrl: 'http://arihant-rmportal-uat.s3-website.ap-south-1.amazonaws.com',
  isProduction: false,
  ekycArihantPlusLogin: 'https://uatmobile.arihantplus.com',
  ekycArihantCapitalLogin: 'https://uatmobile.arihantcapital.com',
  portal: 'Arihant_Plus',
  devRevPrivateKey: '7b39b1e1-eef6-42b5-9acf-3f75e39aacd2',
  isPortalUrlEnable: true,
  panDobVersion: true,
  selfieDomainUrl: 'https://d3gssr2k0zwrrs.cloudfront.net/uat/',
  selfieMode: 'not_hyperverge',
  userExperior: true,
  aiNextSelfiMode: true,
  isOwnPhotoCapture: 'Yes',
  logoutApi: true,
  isCheckGeoLocation: true,
  configExpAccessToken: 180,
  getCookieExpiredTimeAccessToken: 179,
  isRefreshTokenCheck: false,
  setAccessTokenWithExpireTime: true,
  isNomineeProofNumberRequired: true,
  isDDPIConsentRequired: true,
  setAccessTokenExpTime: 8,
  mobileDigiLockerReturnUrl: "https://uat-ws.arihantcapital.com/onboarding-ekyc/onboard/DigiLockerReturnUrl/1.0.0",
  mobileBrokerageReturnUrl: "https://uat-ws.arihantcapital.com/onboarding-ekyc/onboard/BrokerageReturnUrl/1.0.0",
  mobileCamsKRAReturnUrl: "https://dev-ws.arihantcapital.com/onboarding-ekyc/onboard/CamsKRARedirect/1.0.0",
  mobileEsignReturnUrl: "https://dev-ws.arihantcapital.com/onboarding-ekyc/onboard/EKYCRedirect/1.0.0",
};
