export const environment = {
  production: true,
  baseUrl: 'https://9ba9yz5pf9.execute-api.ap-south-1.amazonaws.com/development/', // NEW DB Live
  baseUrlOfUser: 'https://rdcnhy9ag2.execute-api.ap-south-1.amazonaws.com/development/', // NEW DB Live
  image_upload_url: 'https://u9tdfk8o4l.execute-api.ap-south-1.amazonaws.com/development/',   // NEW DB Live
  common_upload: 'https://b1s78nb3zi.execute-api.ap-south-1.amazonaws.com/development/',  //NEW DB Live
  languageParamUrl: 'https://signup.arihantplus.com/assets/', // dev-site Live
  client_id: 'UMC01C9FA0',  // dev-site Live
  redirect_uri: 'https://signup.arihantplus.com/redirect', // dev-site Live
  golapp: 'http://goldapp.getprosper.in', // Gold app Live
  logo_url: 'assets/images/logo-arihant-plus-primary.png', // dev-site Live
  logo_url_wt: 'assets/images/logo-arihant-plus-primary-white.png', // dev-site Live
  login_redirect_page: 'https://www.arihantplus.com',
  explore_web_url: 'https://home.getprosper.in/explore',
  mutualfund_web_url: 'https://home.getprosper.in/product-mutualfund',
  aboutus_web_url: 'https://home.getprosper.in/aboutus',
  home_url: 'https://home.getprosper.in',
  goals_url: 'https://home.getprosper.in/goals',
  calculators_url: 'https://home.getprosper.in/calculators/sip',
  culture_url: 'https://home.getprosper.in/culture',
  career_url: 'https://home.getprosper.in/careers',
  faq_url: 'https://home.getprosper.in/faq/account-opening',
  nfo_url: 'https://home.getprosper.in/nfo',
  googleSignUpUrl: 'https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&prompt=consent&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fplus.me%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&response_type=code&client_id=1083499708270-min6j00pms41kckoojhn9qaea8r1s9pl.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A4200%2Fgoogle',
  facebookSignupUrl: 'https://www.facebook.com/v4.0/dialog/oauth?auth_type=rerequest&client_id=1342908959408435&display=popup&redirect_uri=https%3A%2F%2Fsignin.getprosper.in%2FfaceBook&response_type=code&scope=email',
  appleSignupUrl: 'https://appleid.apple.com/auth/authorize?response_type=code&state=state&client_id=in.getprosper.devsite.service&redirect_uri=https%3A%2F%2Fdevsite.getprosper.in%2FappleRedirect&scope=openid+',
  blogUrl: 'https://blog.arihantcapital.com/mobile-number-not-linked-with-aadhar-card',
  login_type: 'Mobile_OTP',
  client_name: 'arihant',
  esignActionUrl: 'https://esign.egov-nsdl.com/nsdl-esp/authenticate/esign-doc/',
  needHelp: 'https://support.arihantcapital.com/support/solutions/33000138462',
  addressKnowMore: 'https://support.arihantcapital.com/support/solutions/33000138462',
  termsConditionUrl: 'https://www.arihantcapital.com/termsandconditions',
  faqUrl: 'https://support.arihantcapital.com/support/solutions/33000138462',
  clientLogin: 'https://web.arihantplus.com/base/login-name',
  androidLink: 'https://play.google.com/store/apps/details?id=com.msf.acml',
  iosLink: 'https://apps.apple.com/in/app/arihant-plus/id1643484698',
  footerSiteUrl: 'https://arihantcapital.com',
  idArihantPlus: 'arihantplus',
  autoRefresh: 5,
  googleClientID: '14817829564-qq76bi9hba160gis57hsan0p01csrv0o.apps.googleusercontent.com',
  rmRedirectUrl: 'https://signup.arihantplus.com',
  logoutRedirectUrl: 'https://signup.arihantplus.com',
  isProduction: false,
  ekycArihantPlusLogin: 'https://signup.arihantplus.com',
  ekycArihantCapitalLogin: 'https://ekyc.arihantcapital.com',
  portal: 'Arihant_Plus',
  isPortalUrlEnable: true,
  tagManager: true,
  devRevPrivateKey: '76c03250-0d27-49e7-8dc8-31029a5ec45a',
  panDobVersion: true,
  userExperior: true,
  logoutApi: true,
  isCheckGeoLocation: true,
  aiNextSelfiMode: true,
  isOwnPhotoCapture: 'Yes',
  isPaymentEnabled: true,
  configExpAccessToken: 8 * 60,
  getCookieExpiredTimeAccessToken: 8 * 60,
  isNomineeProofNumberRequired: false,
  isDDPIConsentRequired: true,
  isRefreshTokenCheck: false,
  setAccessTokenWithExpireTime: true,
  setAccessTokenExpTime: 8,
  mobileDigiLockerReturnUrl: "https://cug-ws.arihantcapital.com/onboarding-ekyc/onboard/DigiLockerReturnUrl/1.0.0",
  mobileBrokerageReturnUrl: "https://cug-ws.arihantcapital.com/onboarding-ekyc/onboard/BrokerageReturnUrl/1.0.0",
  mobileCamsKRAReturnUrl: "https://cug-ws.arihantcapital.com/onboarding-ekyc/onboard/CamsKRARedirect/1.0.0",
  mobileEsignReturnUrl: "https://cug-ws.arihantcapital.com/onboarding-ekyc/onboard/EKYCRedirect/1.0.0",
};